apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
        type: consumer
    spec:
      containers:
        - name: microservice-b
          image: {{ .Values.microserviceB.image }}
          env:
          - name: DD_DATA_STREAMS_ENABLED
            value: "true"
          - name: DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED
            value: "true"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-b
spec:
  selector:
    app: microservice-b
  ports:
    - port: 80
      targetPort: 80