apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-trigger
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: trigger
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          for i in $(seq 1 180); do
            echo "[$(date)] Sending message..."
            curl -X POST microservice-a/produce \
              -H "Content-Type: application/json" \
              -d '{"message":"hello kafka"}'
            sleep 20
          done
      restartPolicy: Never
  backoffLimit: 0